name: Test and Build

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build